[project]
name = "connections-puzzle-solver"
version = "1.0.0"
description = "NYT Connections Puzzle Solver with drag-and-drop interface"
requires-python = ">=3.8"
dependencies = [
    "flask>=3.0.0",
    "flask-cors>=4.0.0",
    "requests>=2.31.0",
]

[tool.uv]
dev-dependencies = []